### ISSUE TITLE
Error When Running Makefile

### ISSUE THREAD

**Issue by sehf-dev** [legendaryredfox/raylib-lua-bindings#4]
Hi, 
When I run the MakeFile, I seem to get this error 

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lraylib: No such file or directory
collect2.exe: error: ld returned 1 exit status

make: *** [makefile:41: raylib.dll] Error 1
```

It seems the raylib.dll is missing or not found at the correct location. I wondered if I needed to run the raylib installer from itch so I did, but the error continues to accur. 

Idk if I'm missing something from the github page or what, my compiling and Make knowledge are quite lacking so my apologies if this is a waste of time. My operating system is Window 10.

**Comment by legendaryredfox** [comment]
hey, sorry to hear that. do you have mingw and gcc installed? 


Currently the readme is a bit of a mess (I hope I can fix it before xmas). If you have both mingw and gcc installed, try deleting the contents of the Makefile and replace it with the contents of [windows_working_mkf](https://github.com/legendaryredfox/raylib-lua-bindings/blob/main/windows_working_mkf). If the problem persists, please let me know

**Comment by sehf-dev** [comment]
Yep, I have both gcc and mingw installed. And after the Makefile modifications I continue to receive the error ->
 
```
cannot find -lraylib: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:30: raylib.dll] Error 1
```

Is there any way I could have missed something when installing raylib? All I did was run the installer from itch.io.

**Comment by legendaryredfox** [comment]
I don't think the installer is the issue, although I did install raylib from source, using this command: cmake .. -DBUILD_SHARED_LIBS=ON
Please try to compile raylib inside ./raylib

**Comment by sehf-dev** [comment]
Ah I got it working. I went to the raylib github and installed the "raylib-5.5_win64_mingw-w64.zip" version. I then retrieved the header and linker files and added them inside my mingw64 include and lib directories. I guess the installer wasn't actually adding them to my compiler. Thanks for the help :)

**Comment by legendaryredfox** [comment]
Any time!
